[[main]]
name = "Home"
pageRef = "index"
identifier = "KCgx6vYcpW"
weight = 1

[[main]]
name = "My Projects"
pageRef = "projects"
identifier = "eAnHAPmV1V"
weight = 2

[[main]]
name = "My Blog"
pageRef = "blog"
weight = 3

[[main]]
name = "About Me"
pageRef = "about"
identifier = "oH3nAxdPVc"
weight = 4

[[footer]]
name = "Email Me"
url = "mailto:glinek@anulab.tech"

[[footer]]
name = "My Github"
url = "https://github.com/Glinek"
